# Build docs using Sphinx and deploy to GitHub Pages.
name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to GitHub Pages (disable to only test the build)"
        type: boolean
        default: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Install graphviz
        run: |
          sudo apt-get install -y graphviz
      - name: Build and Deploy Documentation
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: "."
          requirements_path: "./requirements.txt"
          publish: ${{ github.event_name == 'push' || github.event.inputs.publish == 'true' }}
